2024-10-05 21:57:32,971 - ERROR - Failed to connect to database: (pyodbc.Error) ('IM012', '[IM012] [Microsoft][ODBC Driver Manager] DRIVER keyword syntax error (0) (SQLDriverConnect)')
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-10-05 21:57:48,293 - ERROR - Failed to connect to database: (pyodbc.Error) ('IM012', '[IM012] [Microsoft][ODBC Driver Manager] DRIVER keyword syntax error (0) (SQLDriverConnect)')
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-10-05 21:58:09,225 - ERROR - Failed to connect to database: (pyodbc.Error) ('IM012', '[IM012] [Microsoft][ODBC Driver Manager] DRIVER keyword syntax error (0) (SQLDriverConnect)')
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-10-05 22:02:58,639 - ERROR - Failed to connect to database: (pyodbc.Error) ('IM012', '[IM012] [Microsoft][ODBC Driver Manager] DRIVER keyword syntax error (0) (SQLDriverConnect)')
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-10-05 22:03:36,945 - ERROR - Failed to connect to database: (pyodbc.Error) ('IM012', '[IM012] [Microsoft][ODBC Driver Manager] DRIVER keyword syntax error (0) (SQLDriverConnect)')
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-10-05 22:07:47,277 - ERROR - Failed to connect to database: (pyodbc.InterfaceError) ('28000', "[28000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Login failed for user 'None'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Login failed for user 'None'. (18456)")
(Background on this error at: https://sqlalche.me/e/20/rvf5)
2024-10-05 22:07:52,437 - ERROR - Failed to connect to database: (pyodbc.InterfaceError) ('28000', "[28000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Login failed for user 'None'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Login failed for user 'None'. (18456)")
(Background on this error at: https://sqlalche.me/e/20/rvf5)
2024-10-05 22:08:10,687 - INFO - Successfully connected to database 'OTAs'.
2024-10-05 22:08:17,307 - INFO - Extracted table name from URL: 'Rome'
2024-10-05 22:08:17,307 - ERROR - Error checking table existence: (pyodbc.ProgrammingError) ('The SQL contains 0 parameter markers, but 1 parameters were supplied', 'HY000')
[SQL: 
    SELECT TABLE_NAME
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_NAME = :table_name
    ]
[parameters: {'table_name': 'Rome'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-10-05 22:08:17,308 - WARNING - Table 'Rome' not found in database 'OTAs'.
2024-10-05 22:08:28,837 - ERROR - Error checking table existence: (pyodbc.ProgrammingError) ('The SQL contains 0 parameter markers, but 1 parameters were supplied', 'HY000')
[SQL: 
    SELECT TABLE_NAME
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_NAME = :table_name
    ]
[parameters: {'table_name': 'Rome'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-10-05 22:08:28,838 - ERROR - Table 'Rome' does not exist. Exiting.
2024-10-05 22:09:12,151 - INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
2024-10-05 22:09:12,171 - INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
2024-10-05 22:09:21,638 - INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
2024-10-05 22:09:21,643 - INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
